[package]
name = "todo_app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "RStodo_app1"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
